export const transportAds = [
    {
        adId: 'ad_1',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'бус',
        availabilityDate: '2024-11-09',
        location: 'Петрозаводск',
        destination: null,
        price: 3491,
        bodyType: 'все закрытые',
        volume: 90,
        loadingType: 'не указан',
        payment: 'б/нал без НДС',
        contactInfo: 'melissa14@shaw.org',
    },
    {
        adId: 'ad_2',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'фура',
        availabilityDate: '2024-11-13',
        location: 'Барнаул',
        destination: 'Набережные Челны',
        price: 2896,
        bodyType: 'все закрытые',
        volume: 30,
        loadingType: 'верхняя',
        payment: 'б/нал без НДС',
        contactInfo: 'jfoster@hotmail.com',
    },
    {
        adId: 'ad_3',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'бус',
        availabilityDate: '2024-11-13',
        location: 'Орск',
        destination: 'Кемерово',
        price: 2329,
        bodyType: 'тентованный',
        volume: 100,
        loadingType: 'не указан',
        payment: 'б/нал с НДС',
        contactInfo: 'palexander@gmail.com',
    },
    {
        adId: 'ad_4',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'фура',
        availabilityDate: '2024-10-27',
        location: 'Хабаровск',
        destination: 'Ульяновск',
        price: 1833,
        bodyType: 'тентованный',
        volume: 30,
        loadingType: 'задняя',
        payment: 'б/нал с НДС',
        contactInfo: 'victoriafrost@hotmail.com',
    },
    {
        adId: 'ad_5',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'бус',
        availabilityDate: '2024-10-31',
        location: 'Благовещенск',
        destination: 'Тверь',
        price: 1280,
        bodyType: 'рефрижератор',
        volume: 50,
        loadingType: 'верхняя',
        payment: 'б/нал без НДС',
        contactInfo: 'brighttimothy@taylor.com',
    },
    {
        adId: 'ad_1',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'микроавтобус',
        availabilityDate: '2024-11-10',
        location: 'Тверь',
        destination: 'Красноярск',
        price: 2132,
        bodyType: 'все открытые',
        volume: 100,
        loadingType: 'с полной растентовкой',
        payment: 'за наличную оплату',
        contactInfo: 'pbrown@rodriguez.com',
    },
    {
        adId: 'ad_2',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'бус',
        availabilityDate: '2024-10-19',
        location: 'Новокузнецк',
        destination: 'Казань',
        price: 2583,
        bodyType: 'все открытые',
        volume: 80,
        loadingType: 'не указан',
        payment: 'б/нал без НДС',
        contactInfo: 'jasonmcdaniel@gmail.com',
    },
    {
        adId: 'ad_3',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'фура',
        availabilityDate: '2024-10-16',
        location: 'Орск',
        destination: 'Санкт-Петербург',
        price: 3324,
        bodyType: 'рефрижератор',
        volume: 50,
        loadingType: 'верхняя',
        payment: 'за наличную оплату',
        contactInfo: 'antonioalexander@hotmail.com',
    },
    {
        adId: 'ad_4',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'бус',
        availabilityDate: '2024-11-03',
        location: 'Воронеж',
        destination: 'Екатеринбург',
        price: 4432,
        bodyType: 'тентованный',
        volume: 90,
        loadingType: 'боковая',
        payment: 'за наличную оплату',
        contactInfo: 'angelahamilton@yahoo.com',
    },
    {
        adId: 'ad_5',
        ownerId: 'bTh6laDni4Yn2J6L6hveFPR6byy2',
        vehicleType: 'грузовик',
        availabilityDate: '2024-11-05',
        location: 'Набережные Челны',
        destination: 'Ижевск',
        price: 4695,
        bodyType: 'все открытые',
        volume: 50,
        loadingType: 'боковая',
        payment: 'б/нал без НДС',
        contactInfo: 'heidi14@hernandez-malone.org',
    },
    {
        adId: 'ad_6',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'бус',
        availabilityDate: '2024-11-11',
        location: 'Астрахань',
        destination: 'Тверь',
        price: 1443,
        bodyType: 'тентованный',
        volume: 40,
        loadingType: 'боковая',
        payment: 'б/нал без НДС',
        contactInfo: 'pjohnson@grimes.com',
    },
    {
        adId: 'ad_7',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'фура',
        availabilityDate: '2024-11-13',
        location: 'Саратов',
        destination: null,
        price: 2474,
        bodyType: 'все открытые',
        volume: 30,
        loadingType: 'с полной растентовкой',
        payment: 'б/нал с НДС',
        contactInfo: 'richardjenkins@edwards.net',
    },
    {
        adId: 'ad_8',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'бус',
        availabilityDate: '2024-10-25',
        location: 'Новосибирск',
        destination: 'Рязань',
        price: 3359,
        bodyType: 'все открытые',
        volume: 20,
        loadingType: 'верхняя',
        payment: 'б/нал с НДС',
        contactInfo: 'inguyen@lamb-murphy.com',
    },
    {
        adId: 'ad_9',
        ownerId: 'bTh6laDni4Yn2J6L6hveFPR6byy2',
        vehicleType: 'бус',
        availabilityDate: '2024-11-03',
        location: 'Смоленск',
        destination: 'Уфа',
        price: 1473,
        bodyType: 'все закрытые',
        volume: 30,
        loadingType: 'верхняя',
        payment: 'б/нал без НДС',
        contactInfo: 'heather99@delgado.com',
    },
    {
        adId: 'ad_10',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'грузовик',
        availabilityDate: '2024-10-19',
        location: 'Ростов-на-Дону',
        destination: null,
        price: 3194,
        bodyType: 'изотерм',
        volume: 70,
        loadingType: 'верхняя',
        payment: 'б/нал без НДС',
        contactInfo: 'charleshowe@elliott.org',
    },
    {
        adId: 'ad_51',
        ownerId: 'bTh6laDni4Yn2J6L6hveFPR6byy2',
        vehicleType: 'микроавтобус',
        availabilityDate: '2024-11-10',
        location: 'Липецк',
        destination: 'Грозный',
        price: 1619,
        bodyType: 'изотерм',
        volume: 90,
        loadingType: 'с полной растентовкой',
        payment: 'за наличную оплату',
        contactInfo: 'xbrock@french.com',
    },
    {
        adId: 'ad_52',
        ownerId: 'bTh6laDni4Yn2J6L6hveFPR6byy2',
        vehicleType: 'микроавтобус',
        availabilityDate: '2024-11-08',
        location: 'Хабаровск',
        destination: 'Ростов-на-Дону',
        price: 4286,
        bodyType: 'все открытые',
        volume: 80,
        loadingType: 'задняя',
        payment: 'б/нал с НДС',
        contactInfo: 'marissanelson@barker-welch.org',
    },
    {
        adId: 'ad_53',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'микроавтобус',
        availabilityDate: '2024-11-12',
        location: 'Нижневартовск',
        destination: null,
        price: 4316,
        bodyType: 'тентованный',
        volume: 20,
        loadingType: 'боковая',
        payment: 'за наличную оплату',
        contactInfo: 'smithjonathan@yahoo.com',
    },
    {
        adId: 'ad_54',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'фура',
        availabilityDate: '2024-11-04',
        location: 'Ульяновск',
        destination: 'Ульяновск',
        price: 1469,
        bodyType: 'рефрижератор',
        volume: 60,
        loadingType: 'верхняя',
        payment: 'за наличную оплату',
        contactInfo: 'elizabeth50@yahoo.com',
    },
    {
        adId: 'ad_55',
        ownerId: 'bTh6laDni4Yn2J6L6hveFPR6byy2',
        vehicleType: 'бус',
        availabilityDate: '2024-10-28',
        location: 'Ульяновск',
        destination: 'Рязань',
        price: 4568,
        bodyType: 'изотерм',
        volume: 60,
        loadingType: 'не указан',
        payment: 'б/нал с НДС',
        contactInfo: 'vasquezsabrina@gonzales-patterson.com',
    },
    {
        adId: 'ad_56',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'фура',
        availabilityDate: '2024-10-30',
        location: 'Саратов',
        destination: null,
        price: 1503,
        bodyType: 'все открытые',
        volume: 30,
        loadingType: 'верхняя',
        payment: 'за наличную оплату',
        contactInfo: 'jasonruiz@edwards.net',
    },
    {
        adId: 'ad_101',
        ownerId: 'bTh6laDni4Yn2J6L6hveFPR6byy2',
        vehicleType: 'фура',
        availabilityDate: '2024-10-20',
        location: 'Чебоксары',
        destination: 'Благовещенск',
        price: 4218,
        bodyType: 'все закрытые',
        volume: 100,
        loadingType: 'с полной растентовкой',
        payment: 'б/нал с НДС',
        contactInfo: 'brenda87@stevens-moore.org',
    },
    {
        adId: 'ad_102',
        ownerId: 'bTh6laDni4Yn2J6L6hveFPR6byy2',
        vehicleType: 'грузовик',
        availabilityDate: '2024-10-22',
        location: 'Новороссийск',
        destination: null,
        price: 3670,
        bodyType: 'все закрытые',
        volume: 50,
        loadingType: 'верхняя',
        payment: 'б/нал без НДС',
        contactInfo: 'sabrina35@smith.org',
    },
    {
        adId: 'ad_103',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'грузовик',
        availabilityDate: '2024-10-27',
        location: 'Волгоград',
        destination: null,
        price: 4134,
        bodyType: 'тентованный',
        volume: 100,
        loadingType: 'боковая',
        payment: 'за наличную оплату',
        contactInfo: 'joseph82@jones-perez.com',
    },
    {
        adId: 'ad_104',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'грузовик',
        availabilityDate: '2024-10-24',
        location: 'Тюмень',
        destination: 'Хабаровск',
        price: 1001,
        bodyType: 'рефрижератор',
        volume: 40,
        loadingType: 'задняя',
        payment: 'б/нал без НДС',
        contactInfo: 'jonesjacob@hayes.biz',
    },
    {
        adId: 'ad_105',
        ownerId: 'RFE2sA5BdYcvhHzLXEwKZoB53Tc2',
        vehicleType: 'микроавтобус',
        availabilityDate: '2024-11-02',
        location: 'Самара',
        destination: 'Благовещенск',
        price: 3108,
        bodyType: 'изотерм',
        volume: 60,
        loadingType: 'верхняя',
        payment: 'за наличную оплату',
        contactInfo: 'imoore@mitchell.info',
    },
    {
        adId: 'ad_106',
        ownerId: 'A9lTs7ZeBsOHADGE1MGlFCKx08u1',
        vehicleType: 'бус',
        availabilityDate: '2024-11-04',
        location: 'Ульяновск',
        destination: null,
        price: 1149,
        bodyType: 'тентованный',
        volume: 40,
        loadingType: 'задняя',
        payment: 'б/нал без НДС',
        contactInfo: 'barnesjimmy@hotmail.com',
    },
];
