export const testAds = [
    {
        adId: 'ad_1',
        ownerId: 'owner_3',
        availabilityDate: '12.10.2024',
        departureCity: 'Москва',
        destinationCity: 'Санкт-Петербург',
        price: 540,
        paymentUnit: 'руб',
        readyToNegotiate: true,
        paymentOptions: ['наличные', 'б/нал с НДС'],
        truckId: 'truck_2',
        truckName: 'Трак №1',
        truckPhotoUrl: '',
        transportType: 'Еврофура',
        loadingTypes: ['верхняя', 'боковая'],
        truckWeight: '6.78',
        truckHeight: '2.00',
        truckWidth: '1.80',
        truckDepth: '1.50',
    },
    {
        adId: 'ad_2',
        ownerId: 'owner_8',
        availabilityDate: '15.10.2024',
        departureCity: 'Екатеринбург',
        destinationCity: 'Нижний Новгород',
        price: 350,
        paymentUnit: 'тыс. руб',
        readyToNegotiate: false,
        paymentOptions: ['б/нал без НДС'],
        truckId: 'truck_5',
        truckName: 'Трак №2',
        truckPhotoUrl: '',
        transportType: 'Изотерм',
        loadingTypes: ['задняя'],
        truckWeight: '8.50',
        truckHeight: '2.50',
        truckWidth: '1.90',
        truckDepth: '1.70',
    },
    {
        adId: 'ad_3',
        ownerId: 'owner_1',
        availabilityDate: '13.10.2024',
        departureCity: 'Казань',
        destinationCity: 'Челябинск',
        price: 670,
        paymentUnit: 'руб/км',
        readyToNegotiate: true,
        paymentOptions: ['наличные', 'б/нал без НДС'],
        truckId: 'truck_1',
        truckName: 'Трак №3',
        truckPhotoUrl: '',
        transportType: 'Рефрижератор',
        loadingTypes: ['гидроборт', 'без ворот'],
        truckWeight: '5.25',
        truckHeight: '2.20',
        truckWidth: '1.85',
        truckDepth: '1.60',
    },
    {
        adId: 'ad_4',
        ownerId: 'owner_7',
        availabilityDate: '18.10.2024',
        departureCity: 'Самара',
        destinationCity: 'Ростов-на-Дону',
        price: 440,
        paymentUnit: 'руб/час',
        readyToNegotiate: false,
        paymentOptions: ['наличные', 'б/нал с НДС'],
        truckId: 'truck_4',
        truckName: 'Трак №4',
        truckPhotoUrl: '',
        transportType: 'Jumbo',
        loadingTypes: ['боковая'],
        truckWeight: '7.40',
        truckHeight: '2.00',
        truckWidth: '1.75',
        truckDepth: '1.55',
    },
    {
        adId: 'ad_5',
        ownerId: 'owner_6',
        availabilityDate: '20.10.2024',
        departureCity: 'Тюмень',
        destinationCity: 'Хабаровск',
        price: 580,
        paymentUnit: 'руб',
        readyToNegotiate: true,
        paymentOptions: ['б/нал с НДС'],
        truckId: 'truck_3',
        truckName: 'Трак №5',
        truckPhotoUrl: '',
        transportType: 'Автосцепка',
        loadingTypes: ['верхняя', 'боковая'],
        truckWeight: '9.00',
        truckHeight: '2.40',
        truckWidth: '2.00',
        truckDepth: '1.80',
    },
    {
        adId: 'ad_6',
        ownerId: 'owner_2',
        availabilityDate: '19.10.2024',
        departureCity: 'Калуга',
        destinationCity: 'Липецк',
        price: 320,
        paymentUnit: 'тыс. руб',
        readyToNegotiate: false,
        paymentOptions: ['наличные', 'б/нал без НДС'],
        truckId: 'truck_2',
        truckName: 'Трак №6',
        truckPhotoUrl: '',
        transportType: 'Цельнометаллическая',
        loadingTypes: ['гидроборт'],
        truckWeight: '4.50',
        truckHeight: '2.10',
        truckWidth: '1.95',
        truckDepth: '1.65',
    },
    {
        adId: 'ad_7',
        ownerId: 'owner_9',
        availabilityDate: '22.10.2024',
        departureCity: 'Ижевск',
        destinationCity: 'Саратов',
        price: 710,
        paymentUnit: 'руб',
        readyToNegotiate: true,
        paymentOptions: ['наличные'],
        truckId: 'truck_1',
        truckName: 'Трак №7',
        truckPhotoUrl: '',
        transportType: 'Открытая платформа',
        loadingTypes: ['верхняя', 'боковая'],
        truckWeight: '8.25',
        truckHeight: '2.50',
        truckWidth: '1.80',
        truckDepth: '1.70',
    },
    {
        adId: 'ad_8',
        ownerId: 'owner_5',
        availabilityDate: '25.10.2024',
        departureCity: 'Нижний Новгород',
        destinationCity: 'Кострома',
        price: 530,
        paymentUnit: 'руб',
        readyToNegotiate: false,
        paymentOptions: ['б/нал с НДС'],
        truckId: 'truck_3',
        truckName: 'Трак №8',
        truckPhotoUrl: '',
        transportType: 'Контейнеровоз',
        loadingTypes: ['задняя'],
        truckWeight: '6.75',
        truckHeight: '2.30',
        truckWidth: '1.90',
        truckDepth: '1.60',
    },
    {
        adId: 'ad_9',
        ownerId: 'owner_4',
        availabilityDate: '28.10.2024',
        departureCity: 'Калининград',
        destinationCity: 'Сочи',
        price: 420,
        paymentUnit: 'руб',
        readyToNegotiate: true,
        paymentOptions: ['наличные', 'б/нал с НДС'],
        truckId: 'truck_2',
        truckName: 'Трак №9',
        truckPhotoUrl: '',
        transportType: 'Автоцистерна',
        loadingTypes: ['гидроборт'],
        truckWeight: '7.10',
        truckHeight: '2.20',
        truckWidth: '1.85',
        truckDepth: '1.50',
    },
    {
        adId: 'ad_10',
        ownerId: 'owner_6',
        availabilityDate: '30.10.2024',
        departureCity: 'Томск',
        destinationCity: 'Уфа',
        price: 650,
        paymentUnit: 'тыс. руб',
        readyToNegotiate: false,
        paymentOptions: ['б/нал с НДС', 'б/нал без НДС'],
        truckId: 'truck_1',
        truckName: 'Трак №10',
        truckPhotoUrl: '',
        transportType: 'Автовоз',
        loadingTypes: ['верхняя'],
        truckWeight: '5.90',
        truckHeight: '2.15',
        truckWidth: '1.95',
        truckDepth: '1.65',
    },
];
